#!/usr/bin/env python3
"""Regenerate content/cac-index.json from the upstream CAC Ontology.

The tracker anchors topics to CAC classes by IRI. To validate those IRIs without
requiring every contributor to clone a second repository, a flattened index of
the ontology is vendored into content/cac-index.json and committed.

This script rebuilds that index. Run it when the upstream ontology publishes a
new version, then commit the diff so reviewers can see exactly which classes
appeared or disappeared.

    git clone --depth 1 https://github.com/Project-VIC-International/CAC-Ontology /tmp/CAC-Ontology
    python3 tools/sync_cac_index.py --ontology-dir /tmp/CAC-Ontology/ontology

Upstream: https://github.com/Project-VIC-International/CAC-Ontology  (Apache-2.0)
Shepherd: Project VIC International
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "content" / "cac-index.json"
UPSTREAM = "https://github.com/Project-VIC-International/CAC-Ontology"

# Turtle in this ontology declares classes as either
#   prefix:Local rdf:type owl:Class ; ... .
# or
#   prefix:Local a owl:Class ; ... .
# Both forms are handled. Blocks end at a blank line or a terminating period.
CLASS_RE = re.compile(
    r'^([A-Za-z][\w-]*):([A-Za-z][\w-]*)\s+(?:rdf:type|a)\s+owl:Class\s*;(.*?)(?:^\s*$|\.\s*$)',
    re.S | re.M)
LABEL_RE = re.compile(r'rdfs:label\s+"((?:[^"\\]|\\.)*)"')
COMMENT_RE = re.compile(r'rdfs:comment\s+"((?:[^"\\]|\\.)*)"')
SUB_RE = re.compile(r'rdfs:subClassOf\s+([A-Za-z][\w-]*:[A-Za-z][\w-]*)')
PREFIX_RE = re.compile(r'^@prefix\s+([A-Za-z][\w-]*):\s*<([^>]+)>\s*\.', re.M)
ONTDECL_RE = re.compile(r'<([^>]+)>\s+rdf:type\s+owl:Ontology\s*;(.*?)\.\s*$', re.S | re.M)
VERSION_RE = re.compile(r'owl:versionInfo\s+"([^"]+)"')


def extract(ontology_dir: Path) -> dict:
    modules, classes = [], []

    ttl_files = sorted(ontology_dir.glob("*.ttl"))
    if not ttl_files:
        sys.exit(f"No .ttl files found in {ontology_dir}")

    for f in ttl_files:
        if "shapes" in f.name:
            continue  # SHACL shapes constrain classes, they do not define them
        text = f.read_text(encoding="utf-8", errors="replace")
        prefixes = dict(PREFIX_RE.findall(text))

        decl = ONTDECL_RE.search(text)
        header = decl.group(2) if decl else ""
        lab = LABEL_RE.search(header)
        ver = VERSION_RE.search(header)

        module_id = f.stem.replace("cacontology-", "")
        found = 0
        for pfx, local, body in CLASS_RE.findall(text):
            ns = prefixes.get(pfx)
            if not ns or "cacontology.projectvic.org" not in ns:
                continue  # only index CAC's own classes, not imported UCO/CASE/gUFO
            cl, cm = LABEL_RE.search(body), COMMENT_RE.search(body)
            classes.append({
                "module": module_id,
                "prefix": pfx,
                "local": local,
                "iri": ns + local,
                "label": cl.group(1) if cl else local,
                "comment": (cm.group(1) if cm else "").strip(),
                "subClassOf": sorted(set(SUB_RE.findall(body))),
            })
            found += 1

        if found:
            modules.append({
                "id": module_id,
                "file": f.name,
                "label": lab.group(1) if lab else f.stem,
                "version": ver.group(1) if ver else None,
                "class_count": found,
            })

    return {
        "_meta": {
            "source": UPSTREAM,
            "license": "Apache-2.0",
            "shepherd": "Project VIC International",
            "namespace": "https://cacontology.projectvic.org",
            "module_count": len(modules),
            "class_count": len(classes),
            "note": "Generated by tools/sync_cac_index.py. Do not edit by hand.",
        },
        "modules": sorted(modules, key=lambda m: m["id"]),
        "classes": sorted(classes, key=lambda c: (c["module"], c["local"])),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ontology-dir", type=Path, required=True,
                    help="path to the CAC-Ontology repo's ontology/ directory")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    index = extract(args.ontology_dir)

    previous: dict = {}
    if args.out.exists():
        try:
            previous = json.loads(args.out.read_text(encoding="utf-8"))
        except Exception:
            previous = {}

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"Wrote {args.out.relative_to(ROOT)}")
    print(f"  modules  {index['_meta']['module_count']}")
    print(f"  classes  {index['_meta']['class_count']}")

    if previous.get("classes"):
        before = {c["iri"] for c in previous["classes"]}
        after = {c["iri"] for c in index["classes"]}
        added, removed = after - before, before - after
        print(f"  added    {len(added)}")
        print(f"  removed  {len(removed)}")
        for iri in sorted(removed)[:20]:
            print(f"    - {iri}")
        if removed:
            print("\n  Removed classes may be referenced by topics. Run tools/validate.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
